// This file is automatically generated by i18next-cli, because it was not existing. You can edit it based on your needs: https://www.i18next.com/overview/typescript#custom-type-options

// Make sure the interface CustomTypeOptions has these 2 properties to maintain consistency with the project:
// `returnNull: false`, `returnEmptyString: false`.
import Resources from './resources';

declare module 'i18next' {
  interface CustomTypeOptions {
    enableSelector: false;
    defaultNS: 'translation';
    resources: Resources;
    returnNull: false
    returnEmptyString: false
  }
}
