version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod"
    directory: "/api"
    schedule:
      interval: "weekly"

  # Maintain dependencies for npm (TypeScript/JavaScript)
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
