version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod"
    directory: "/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 999

  # Maintain dependencies for npm (TypeScript/JavaScript)
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 999
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"

  # Maintain dependencies for Dockerfiles
  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/dependencies"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "node"

  # Maintain dependencies for Docker Compose
  - package-ecosystem: "docker-compose"
    directories:
      - "/docker-compose example"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "node"
