name: Docker builds

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
    tags:
      - v*

env:
  DOCKER_USERNAME: kkoval
  DOCKER_IMAGE: kkoval/photoview
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.target_platform }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        if: success() && github.event_name != 'pull_request' && github.repository == 'kkovaletp/photoview'
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: ${{ env.DOCKER_IMAGE }}
          # Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set Build Args
        id: vars
        run: |
          echo "::set-output name=BUILD_DATE::$(date +%Y-%m-%d)"
          echo "::set-output name=VERSION::kkoval-2-$(date +%Y-%m-%d)"

      - name: Build and push
        id: docker_buildx
        uses: docker/build-push-action@v5
        with:
          context: .
          sbom: true
          provenance: mode=max
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: ${{ github.event_name != 'pull_request' && github.repository == 'kkovaletp/photoview' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ steps.vars.outputs.BUILD_DATE }}
            REACT_APP_BUILD_DATE=${{ steps.vars.outputs.BUILD_DATE }}
            VERSION=${{ steps.vars.outputs.VERSION }}
            REACT_APP_BUILD_VERSION=${{ steps.vars.outputs.VERSION }}
            COMMIT_SHA=${{ github.sha }}
            REACT_APP_BUILD_COMMIT_SHA=${{ github.sha }}
