name: Dependencies builds

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # At 23:18 every Wednesday, 2 hours before `photoview`. Details in https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
    - cron: '18 23 * * 3'

env:
  IS_PUSHING_IMAGES: ${{ github.event_name != 'pull_request' && github.repository == 'kkovaletp/photoview' }}
  IS_CACHING: true
  DOCKER_USERNAME: kkoval
  DOCKER_IMAGE: kkoval/dependencies
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build:
    name: Build Dependencies Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        if: ${{ env.IS_PUSHING_IMAGES == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: ${{ env.DOCKER_IMAGE }}
          # Docker tags based on the following events/attributes
          tags: |
            type=raw,value=latest
            type=sha

      - name: Detect dependency versions
        id: versions
        working-directory: dependencies
        run: |
          docker build \
            --target version-detector \
            --secret id=github_token,src=<(echo "${{ secrets.GITHUB_TOKEN }}") \
            -t version-detector .
          docker run --name version-detector version-detector
          docker cp version-detector:/versions.env ./
          docker rm version-detector
          cat ./versions.env
          cat ./versions.env >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context:     ./dependencies
          platforms:   ${{ env.PLATFORMS }}
          pull:        true
          push:        ${{ env.IS_PUSHING_IMAGES }}
          tags:        ${{ steps.docker_meta.outputs.tags }}
          labels:      ${{ steps.docker_meta.outputs.labels }}
          annotations: ${{ steps.docker_meta.outputs.annotations }}
          no-cache:    ${{ env.IS_CACHING != 'true' }}
          cache-from:  type=gha,scope=deps-${{ steps.versions.outputs.COMBINED_VERSION }}
          cache-to:    type=gha,mode=max,scope=deps-${{ steps.versions.outputs.COMBINED_VERSION }}
          sbom:        true
          provenance:  mode=max
          secrets: |
            github_token=${{ secrets.GITHUB_TOKEN }}
          build-args: |
            LIBRAW_VERSION=${{ steps.versions.outputs.LIBRAW_VERSION }}
            LIBHEIF_VERSION=${{ steps.versions.outputs.LIBHEIF_VERSION }}
            IMAGEMAGICK_VERSION=${{ steps.versions.outputs.IMAGEMAGICK_VERSION }}
            JELLYFIN_FFMPEG_VERSION=${{ steps.versions.outputs.JELLYFIN_FFMPEG_VERSION }}
